<a href="https://colab.research.google.com/github/muajnstu/Large_Scale_Implementation_of_DSK_Chain/blob/main/Data_Preparation_of_Extended_Kaggle_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.8.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.15.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.8.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 1.5 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.8.1

In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from category_encoders import TargetEncoder
from sklearn.impute import SimpleImputer

In [ ]:
# load the data
df = pd.read_csv('https://raw.githubusercontent.com/muajnstu/Implementation-of-Active-Learning-Method-in-Regression-Model/refs/heads/main/Preprocessed_dataset_3_.csv')

In [ ]:
df.head()

,applicant_id,years_of_insurance_with_us,regular_checkup_lasy_year,adventure_sports,Occupation,visited_doctor_last_1_year,cholesterol_level,daily_avg_steps,age,heart_decs_history,...,smoking_status,Year_last_admitted,Location,weight,covered_by_any_other_company,Alcohol,exercise,weight_change_in_last_one_year,fat_percentage,insurance_cost
0,5000.0,3.0,1.0,1.0,2,2.0,137.5,4866.0,28.0,1.0,...,3,2003.892217,27475.538646,67.0,0,1,1,1.0,25.0,20978.0
1,5001.0,0.0,0.0,0.0,0,4.0,162.5,6411.0,50.0,0.0,...,1,2003.892217,27139.320047,58.0,0,1,1,3.0,27.0,6170.0
2,5002.0,1.0,0.0,0.0,1,4.0,212.5,4509.0,68.0,0.0,...,1,2003.892217,27139.320047,73.0,0,2,2,0.0,32.0,28382.0
3,5003.0,7.0,4.0,0.0,1,2.0,187.5,6214.0,51.0,0.0,...,3,2003.892217,27475.538646,71.0,1,1,0,3.0,37.0,27148.0
4,5004.0,3.0,1.0,0.0,0,2.0,162.5,4938.0,44.0,0.0,...,0,2004.000000,26729.346728,74.0,0,0,2,0.0,34.0,29616.0

# Basic EDA

In [ ]:
df.drop(['applicant_id'], axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   applicant_id                    25000 non-null  int64
 1   years_of_insurance_with_us      25000 non-null  int64
 2   regular_checkup_lasy_year       25000 non-null  int64
 3   adventure_sports                25000 non-null  int64
 4   Occupation                      25000 non-null  object
 5   visited_doctor_last_1_year      25000 non-null  int64
 6   cholesterol_level               25000 non-null  object
 7   daily_avg_steps                 25000 non-null  int64
 8   age                             25000 non-null  int64
 9   heart_decs_history              25000 non-null  int64
 10  other_major_decs_history        25000 non-null  int64
 11  Gender                          25000 non-null  object
 12  avg_glucose_level               25000 non-null  int64
 13  bmi                             24010 non-null  float64
 14  smoking_status                  25000 non-null  object
 15  Year_last_admitted              13119 non-null  float64
 16  Location                        25000 non-null  object
 17  weight                          25000 non-null  int64
 18  covered_by_any_other_company    25000 non-null  object
 19  Alcohol                         25000 non-null  object
 20  exercise                        25000 non-null  object
 21  weight_change_in_last_one_year  25000 non-null  int64
 22  fat_percentage                  25000 non-null  int64
 23  insurance_cost                  25000 non-null  int64
dtypes: float64(2), int64(14), object(8)
memory usage: 4.6+ MB

In [ ]:
print(df.isnull().sum())
numerical_cols = df.select_dtypes(include=np.number).columns
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
df[numerical_cols] = imputer.fit_transform(df[numerical_cols])
print("\nAfter imputation:")
print(df.isnull().sum())

applicant_id                          0
years_of_insurance_with_us            0
regular_checkup_lasy_year             0
adventure_sports                      0
Occupation                            0
visited_doctor_last_1_year            0
cholesterol_level                     0
daily_avg_steps                       0
age                                   0
heart_decs_history                    0
other_major_decs_history              0
Gender                                0
avg_glucose_level                     0
bmi                                 990
smoking_status                        0
Year_last_admitted                11881
Location                              0
weight                                0
covered_by_any_other_company          0
Alcohol                               0
exercise                              0
weight_change_in_last_one_year        0
fat_percentage                        0
insurance_cost                        0
dtype: int64

After imputation:
applicant_id                      0
years_of_insurance_with_us        0
regular_checkup_lasy_year         0
adventure_sports                  0
Occupation                        0
visited_doctor_last_1_year        0
cholesterol_level                 0
daily_avg_steps                   0
age                               0
heart_decs_history                0
other_major_decs_history          0
Gender                            0
avg_glucose_level                 0
bmi                               0
smoking_status                    0
Year_last_admitted                0
Location                          0
weight                            0
covered_by_any_other_company      0
Alcohol                           0
exercise                          0
weight_change_in_last_one_year    0
fat_percentage                    0
insurance_cost                    0
dtype: int64

In [ ]:
#function to convert range strings to their mean
def range_to_mean(range_str):
    try:

        return float(range_str)
    except ValueError:
        if isinstance(range_str, str):
            if '-' in range_str:
                low, high = map(float, range_str.split('-'))
            elif ' to ' in range_str:
                low, high = map(float, range_str.split(' to '))
            else:
                return np.nan
            return (low + high) / 2
        else:
            return np.nan
df['cholesterol_level'] = df['cholesterol_level'].apply(range_to_mean)

In [ ]:
df

,applicant_id,years_of_insurance_with_us,regular_checkup_lasy_year,adventure_sports,Occupation,visited_doctor_last_1_year,cholesterol_level,daily_avg_steps,age,heart_decs_history,...,smoking_status,Year_last_admitted,Location,weight,covered_by_any_other_company,Alcohol,exercise,weight_change_in_last_one_year,fat_percentage,insurance_cost
0,5000.0,3.0,1.0,1.0,Salried,2.0,137.5,4866.0,28.0,1.0,...,Unknown,2003.892217,Chennai,67.0,N,Rare,Moderate,1.0,25.0,20978.0
1,5001.0,0.0,0.0,0.0,Student,4.0,162.5,6411.0,50.0,0.0,...,formerly smoked,2003.892217,Jaipur,58.0,N,Rare,Moderate,3.0,27.0,6170.0
2,5002.0,1.0,0.0,0.0,Business,4.0,212.5,4509.0,68.0,0.0,...,formerly smoked,2003.892217,Jaipur,73.0,N,Daily,Extreme,0.0,32.0,28382.0
3,5003.0,7.0,4.0,0.0,Business,2.0,187.5,6214.0,51.0,0.0,...,Unknown,2003.892217,Chennai,71.0,Y,Rare,No,3.0,37.0,27148.0
4,5004.0,3.0,1.0,0.0,Student,2.0,162.5,4938.0,44.0,0.0,...,never smoked,2004.000000,Bangalore,74.0,N,No,Extreme,0.0,34.0,29616.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,29995.0,3.0,0.0,0.0,Salried,4.0,237.5,5614.0,22.0,0.0,...,smokes,2000.000000,Kanpur,79.0,Y,Rare,Moderate,4.0,40.0,39488.0
24996,29996.0,6.0,0.0,0.0,Business,4.0,212.5,4719.0,58.0,0.0,...,never smoked,2009.000000,Kanpur,66.0,N,Rare,Moderate,2.0,28.0,14808.0
24997,29997.0,7.0,0.0,1.0,Student,2.0,162.5,5624.0,34.0,0.0,...,Unknown,2003.892217,Bhubaneswar,76.0,N,Rare,Moderate,1.0,35.0,33318.0
24998,29998.0,1.0,0.0,0.0,Salried,2.0,237.5,10777.0,27.0,0.0,...,Unknown,2003.892217,Surat,74.0,N,Rare,Moderate,0.0,40.0,30850.0
24999,29999.0,8.0,2.0,0.0,Business,4.0,162.5,5882.0,22.0,1.0,...,formerly smoked,2014.000000,Chennai,57.0,N,No,No,4.0,21.0,6170.0

In [ ]:
for col in df.columns:
    print(f"Unique values in column '{col}': {df[col].unique()}")

Unique values in column 'applicant_id': [ 5000.  5001.  5002. ... 29997. 29998. 29999.]
Unique values in column 'years_of_insurance_with_us': [3. 0. 1. 7. 8. 4. 6. 5. 2.]
Unique values in column 'regular_checkup_lasy_year': [1. 0. 4. 3. 2. 5.]
Unique values in column 'adventure_sports': [1. 0.]
Unique values in column 'Occupation': ['Salried' 'Student' 'Business']
Unique values in column 'visited_doctor_last_1_year': [ 2.  4.  3.  5.  1.  8.  7.  6. 10.  9. 12.  0.]
Unique values in column 'cholesterol_level': [137.5 162.5 212.5 187.5 237.5]
Unique values in column 'daily_avg_steps': [ 4866.  6411.  4509. ...  7171.  6808. 10777.]
Unique values in column 'age': [28. 50. 68. 51. 44. 39. 40. 46. 45. 38. 35. 49. 30. 71. 54. 20. 62. 23.
 33. 34. 65. 25. 55. 60. 29. 63. 18. 26. 24. 47. 19. 57. 67. 32. 58. 69.
 53. 70. 41. 43. 48. 31. 72. 52. 42. 59. 17. 61. 36. 66. 56. 21. 74. 64.
 22. 27. 16. 37. 73.]
Unique values in column 'heart_decs_history': [1. 0.]
Unique values in column 'other_major_decs_history': [0. 1.]
Unique values in column 'Gender': ['Male' 'Female']
Unique values in column 'avg_glucose_level': [ 97. 212. 166. 109. 118. 155.  80. 245. 126.  83. 156. 227.  98. 247.
 135. 195. 235. 265. 163. 193.  68. 158. 203.  84. 146.  70. 233. 102.
 157. 267. 232. 167. 199.  85. 129.  82. 100. 218. 252. 169. 224. 136.
 221.  87. 244. 192. 258.  69. 234.  79. 170. 225. 116.  71. 243. 240.
 184.  94.  61. 261. 262.  89. 178. 215. 161. 108.  57. 263.  76. 183.
 223. 114. 275. 130. 237. 185. 175. 172.  99. 162. 147. 264. 209.  65.
 257. 231. 250.  81. 254. 181.  72. 238. 176. 113.  95. 228. 149.  91.
 134. 202. 151. 104. 191.  62. 120. 204. 219. 103. 110. 139. 137. 123.
  86. 259. 208. 186. 236. 165. 241.  93. 266. 148. 190. 248. 217. 270.
 216. 201. 174. 200. 164. 229. 194. 220. 160. 154. 197. 171.  96. 272.
 274. 143. 268. 124. 207. 205.  66. 141. 214.  73.  92. 213.  63. 105.
 196. 122. 188. 101. 179. 271. 132. 153.  67.  64. 111. 251. 260. 152.
 159. 239. 128. 269. 182. 256. 168. 133. 180.  78. 117. 226. 119. 276.
 121. 140.  90. 249.  77. 230. 210. 273. 107. 253. 187. 138. 242.  74.
  59. 131. 106. 206. 173. 222. 142. 198. 127.  60. 115.  75. 145. 189.
 125. 246.  58. 150.  88. 177. 211. 255. 112. 144. 277.]
Unique values in column 'bmi': [ 31.2         34.2         40.4         22.9         26.5
  38.          28.7         26.          24.4         46.
  39.2         19.          29.6         38.9         21.1
  30.4         24.3         25.3         25.7         43.6
  33.8         27.1         40.3         34.3         32.9
  23.2         26.6         20.          20.9         31.3
  26.9         47.9         32.5         31.4         34.8
  45.9         34.1         31.39332778  27.6         30.2
  23.4         41.          33.4         42.2         41.7
  29.4         25.4         24.5         33.6         21.6
  29.7         27.3         22.1         35.8         20.1
  32.8         31.9         27.7         18.1         23.5
  27.2         21.4         37.5         31.8         24.2
  30.5         30.          40.5         39.9         13.3
  22.8         36.7         34.5         33.          39.5
  36.          29.8         45.4         29.          30.7
  28.          24.8         18.8         24.9         28.1
  29.2         41.6         32.3         35.4         35.3
  29.9         26.3         21.8         29.1         45.8
  25.2         13.5         34.          20.4         33.3
  24.7         35.2         36.2         35.6         26.8
  26.2         33.7         27.8         42.6         41.2
  39.4         33.5         40.9         40.          43.7
  27.4         20.2         20.7         37.8         46.7
  34.9         24.          20.6         32.6         31.
  43.3         23.3         32.1         30.6         50.3
  30.9         37.9         34.4         37.2         42.5
  41.8         21.          37.          28.3         22.2
  22.6         40.1         40.7         36.4         28.9
  29.5         38.3         19.6         42.4         48.4
  42.9         26.4         24.1         28.8         31.6
  49.6         35.5         32.          24.6         31.1
  43.1         23.8         37.1         52.3         39.8
  38.5         38.8         44.3         63.6         30.8
  18.          31.5         17.1         17.8         42.1
  34.6         23.          48.5         50.5         36.1
  46.6         51.8         47.5         30.3         49.2
  22.7         41.1         26.7         35.1         44.6
  40.8         28.4         43.4         47.7         38.2
  20.8         27.5         22.4         29.3         25.
  45.6         32.4         17.9         37.4         27.9
  26.1         34.7         22.5         37.6         21.2
  35.          57.7         33.1         48.3         31.7
  16.8         18.3         30.1         55.8         99.6
  27.          28.2         37.3         49.8         36.5
  21.3         22.          25.1         42.          25.6
  43.9         52.8         23.6         44.8         19.9
  46.9         38.4         43.          47.2         19.7
  49.4         18.9         48.9         37.7         23.7
  23.1         33.9         25.9         39.3         16.6
  33.2         40.6         45.2         51.5         46.1
  25.8         35.9         35.7         17.          21.9
  48.7         22.3         46.4         47.8         20.5
  46.8         28.5         36.3         41.4         19.2
  45.          19.1         41.5         25.5         55.7
  18.6         40.2         32.2         36.8         42.3
  36.9         43.2         16.5         54.8         45.1
  44.5         28.6         17.3         42.7         23.9
  41.9         56.7         38.1         44.1         43.5
  54.7         21.5         47.1         41.3         39.
  19.4         50.8         38.7         39.7         49.1
  55.5         63.9         21.7         55.9         18.2
  18.7         39.6         47.4         50.6         47.3
  39.1         47.6         14.3         16.2         50.4
  19.3         58.2         49.3         44.          48.1
  12.3         16.9         46.3         54.          38.6
  19.8         60.2         15.8         58.1         49.5
  44.7         17.2         36.6         56.5         14.5
  48.8         42.8         43.8         17.5         19.5
  32.7         80.          58.7         51.4         20.3
  53.9         44.9         18.4         18.5         46.5
  47.          45.3         58.6         50.7         44.2
  52.5         48.          59.1         57.          50.1
  51.9         53.5         45.7         51.7         56.6
  56.8         16.3         95.          66.8         61.7
  15.9         59.          50.9         66.4         44.4
  15.5         62.7         48.2         52.2         54.5
  54.9         45.5         52.1         17.6         58.9
  15.3         53.2         15.          67.8         53.7
  15.7         59.2         14.8         17.7         57.6
  56.3         51.2         74.9         67.4         15.4
  17.4         51.3         60.3         52.4         55.4
  53.1         16.7         60.9         16.4         63.2
  53.8         94.          15.2         60.5         53.3
  53.4         58.          60.7         57.9         59.3
  64.6         16.          46.2        100.6         59.9
  56.2         16.1         56.1         48.6         52.6
  51.          52.9         57.8         14.          61.1
  59.5         49.          50.2         51.1         55.3
  56.4         53.          56.          57.1         57.2
  49.9         68.8         59.7         66.3         50.
  62.2         69.8         65.3         59.6         62.9
  57.3         73.9         53.6         56.9         54.3
  64.2       ]
Unique values in column 'smoking_status': ['Unknown' 'formerly smoked' 'never smoked' 'smokes']
Unique values in column 'Year_last_admitted': [2003.89221739 2004.         2003.         2007.         1994.
 2010.         2017.         2002.         1996.         2008.
 1991.         1995.         2001.         2013.         2011.
 2005.         2018.         1998.         1997.         1999.
 1992.         2012.         2009.         2014.         2000.
 1993.         2016.         2006.         2015.         1990.        ]
Unique values in column 'Location': ['Chennai' 'Jaipur' 'Bangalore' 'Bhubaneswar' 'Guwahati' 'Mumbai' 'Nagpur'
 'Surat' 'Pune' 'Kanpur' 'Mangalore' 'Kolkata' 'Delhi' 'Ahmedabad'
 'Lucknow']
Unique values in column 'weight': [67. 58. 73. 71. 74. 78. 81. 72. 63. 65. 61. 75. 56. 83. 76. 69. 84. 82.
 64. 62. 66. 52. 59. 87. 88. 57. 90. 80. 77. 91. 70. 86. 68. 60. 53. 92.
 55. 85. 94. 79. 54. 89. 95. 96. 93.]
Unique values in column 'covered_by_any_other_company': ['N' 'Y']
Unique values in column 'Alcohol': ['Rare' 'Daily' 'No']
Unique values in column 'exercise': ['Moderate' 'Extreme' 'No']
Unique values in column 'weight_change_in_last_one_year': [1. 3. 0. 2. 4. 5. 6.]
Unique values in column 'fat_percentage': [25. 27. 32. 37. 34. 13. 16. 12. 38. 11. 21. 19. 22. 31. 29. 18. 24. 33.
 36. 39. 20. 23. 40. 42. 17. 35. 41. 30. 15. 26. 28. 14.]
Unique values in column 'insurance_cost': [20978.  6170. 28382. 27148. 29616. 39488. 37020. 22212.  8638. 25914.
 17276. 14808. 46892. 33318. 49360. 18510. 32084. 12340.  3702.  9872.
 55530.  4936. 51828. 23446.  7404. 57998. 38254. 24680. 60466. 54296.
 34552. 16042. 30850. 41956. 13574. 43190. 48126. 19744. 56764. 35786.
 11106. 61700. 44424. 40722. 59232. 53062. 64168. 62934. 45658. 50594.
 65402. 66636. 67870.  2468.]

In [ ]:
#Encoding

occupation_map = {'Student': 0,'Business': 1, 'Salried': 2}
df['Occupation'] = df['Occupation'].map(occupation_map)
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
df['Alcohol'] = df['Alcohol'].map({'No': 0, 'Rare': 1, 'Daily': 2})
df['exercise'] = df['exercise'].map({'No': 0, 'Moderate': 1, 'Extreme': 2})
smoking_map = {'never smoked': 0,'formerly smoked': 1,'smokes': 2,'Unknown': 3}
df['smoking_status'] = df['smoking_status'].map(smoking_map)

# Target encode Location
target_encoder = TargetEncoder()
df['Location'] = target_encoder.fit_transform(df['Location'], df['insurance_cost'])

In [ ]:
coverage_map = {'N': 0,'Y': 1}
df['covered_by_any_other_company'] = df['covered_by_any_other_company'].map(coverage_map)

In [ ]:
df

,applicant_id,years_of_insurance_with_us,regular_checkup_lasy_year,adventure_sports,Occupation,visited_doctor_last_1_year,cholesterol_level,daily_avg_steps,age,heart_decs_history,...,smoking_status,Year_last_admitted,Location,weight,covered_by_any_other_company,Alcohol,exercise,weight_change_in_last_one_year,fat_percentage,insurance_cost
0,5000.0,3.0,1.0,1.0,2,2.0,137.5,4866.0,28.0,1.0,...,3,2003.892217,27475.538646,67.0,0,1,1,1.0,25.0,20978.0
1,5001.0,0.0,0.0,0.0,0,4.0,162.5,6411.0,50.0,0.0,...,1,2003.892217,27139.320047,58.0,0,1,1,3.0,27.0,6170.0
2,5002.0,1.0,0.0,0.0,1,4.0,212.5,4509.0,68.0,0.0,...,1,2003.892217,27139.320047,73.0,0,2,2,0.0,32.0,28382.0
3,5003.0,7.0,4.0,0.0,1,2.0,187.5,6214.0,51.0,0.0,...,3,2003.892217,27475.538646,71.0,1,1,0,3.0,37.0,27148.0
4,5004.0,3.0,1.0,0.0,0,2.0,162.5,4938.0,44.0,0.0,...,0,2004.000000,26729.346728,74.0,0,0,2,0.0,34.0,29616.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,29995.0,3.0,0.0,0.0,2,4.0,237.5,5614.0,22.0,0.0,...,2,2000.000000,26958.153846,79.0,1,1,1,4.0,40.0,39488.0
24996,29996.0,6.0,0.0,0.0,1,4.0,212.5,4719.0,58.0,0.0,...,0,2009.000000,26958.153846,66.0,0,1,1,2.0,28.0,14808.0
24997,29997.0,7.0,0.0,1.0,0,2.0,162.5,5624.0,34.0,0.0,...,3,2003.892217,27488.363850,76.0,0,1,1,1.0,35.0,33318.0
24998,29998.0,1.0,0.0,0.0,2,2.0,237.5,10777.0,27.0,0.0,...,3,2003.892217,27129.361863,74.0,0,1,1,0.0,40.0,30850.0
24999,29999.0,8.0,2.0,0.0,1,4.0,162.5,5882.0,22.0,1.0,...,1,2014.000000,27475.538646,57.0,0,0,0,4.0,21.0,6170.0

In [ ]:
df.info()

In [ ]:
df.to_csv('cleaned_dataset.csv', index=False)
print("DataFrame saved to 'processed_data.csv'")
from google.colab import files
files.download('cl_dataset_3.csv')

DataFrame saved to 'processed_data.csv'